name: exercises
version: 0.0.1.0
license: MIT

ghc-options: -Wall

dependencies:
  - base
  - text

library:
  source-dirs: src
  dependencies:
    - deepseq
    - directory
    - filepath
    - hint
    - HUnit
    - QuickCheck
    - resourcet

executables:
  exercises-cli:
    main: app/CliMain.hs
    dependencies:
      - exercises
      - haskeline
      - random-shuffle

  exercises-web:
    main: app/WebMain.hs
    dependencies:
      - containers
      - exercises
      - http-types
      - lens
      - scotty
