name: exercises
version: 0.0.1.0
license: MIT

ghc-options: -Wall

default-extensions: NoImplicitPrelude

dependencies:
  - base
  - containers
  - directory
  - filepath
  - haskeline
  - hint
  - HUnit
  - protolude
  - QuickCheck
  - random-shuffle
  - resourcet
  - temporary
  - text

library:
  source-dirs: src

executables:
  exercises:
    main: Main.hs
    source-dirs: app
