name: exercises
version: 0.0.1.0
license: MIT

ghc-options: -Wall

default-extensions: NoImplicitPrelude

dependencies:
  - base
  - protolude
  - text

library:
  source-dirs: src
  dependencies:
    - directory
    - filepath
    - hint
    - HUnit
    - QuickCheck
    - resourcet

executables:
  exercises:
    main: Main.hs
    source-dirs: app
    dependencies:
      - exercises
      - haskeline
      - random-shuffle
