name: exercises
version: 0.0.1.0
license: MIT

ghc-options: -Wall

dependencies:
  - base
  - containers
  - filepath
  - haskeline
  - hint
  - QuickCheck
  - random-shuffle
  - resourcet
  - temporary
  - text

executables:
  exercises:
    main: Main.hs
